config/routes.rb
ROR::Application.routes.draw do
  
  resources :genes
  

  

end

app/models/gene.rb
class Gene < ActiveRecord::Base
  validates :filename, presence: true
  
  # attr_reader :source_file zamiast linii 7
  # attr_writer :source_file zamiast linii 7
  
  attr_accessor :source_file #pozwala wszystko zamkomentowac
  
  #def source_file=(file)  zamiast linii 4
  #  @source_file = file
  #end
  
  # def source_file  zamiast linii 5
    # @source_file
  # end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genes_controller.rb
class GenesController < ApplicationController
	def index
		@genes = Gene.all
	end
	
	def new
	  @gene = Gene.new
	end
	
	def create
	  gene_params = params.require(:gene).permit(:filename, :source_file)
	
	  @gene = Gene.new(gene_params)
	  if @gene.save
	    redirect_to genes_path
	  else
	    render :new
	  end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genes_helper.rb
module GenesHelper
end

app/views/genes/index.html.erb
<div class="panel panel-default">
	<div class="panel-heading"> Nazwy genow </div>
	<div class="panel-body">
		<ul>
			<% @genes.each do |gene| %>
			<li>
				<dl>
					<dd> <%= gene.filename %> </dd>
				</dl>
			</li>
			<% end %>
		</ul>
		
		<li> <%= link_to "Dodaj nowy plik", new_gene_path %> </li>
		
	</div>
</div>

app/views/genes/new.html.erb
<h2> Dodaj nowy plik </h2>

<p></p>
<label for="exampleInputFile">Nazwa pliku</label>
<%= form_for(@gene) do |form| %>

  <div class: "form-group">
    <%= form.text_field :filename, class: "form-control" %>
  </div>
  
  <div class: "form-group">
    <%= form.label :source_file %>
    <%= form.file_field :source_file, class: "form-control" %>
    
    <% if @gene.errors.any? %> 
      <span class="help-block"> <%= @gene.errors[:filename].first %> </span>
    <% end %>
  </div>
    <%= form.submit "Zatwierdz"%>
</form>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ROR</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>